export const ESSENTIAL_ADHKAR = [
  {
    arabic: 'سُبْحَانَ اللّٰهِ',
    transliteration: 'Subḥān Allāh',
    translation: {
      en: 'Glory be to Allah',
      ar: 'سبحان الله',
      ur: 'اللہ پاک ہے',
    },
    recommendedCount: 33,
  },
  {
    arabic: 'الْحَمْدُ لِلّٰهِ',
    transliteration: 'Al-ḥamdu lillāh',
    translation: {
      en: 'All praise is due to Allah',
      ar: 'الحمد لله',
      ur: 'تمام تعریفیں اللہ کے لیے ہیں',
    },
    recommendedCount: 33,
  },
  {
    arabic: 'اللّٰهُ أَكْبَرُ',
    transliteration: 'Allāhu akbar',
    translation: {
      en: 'Allah is the Greatest',
      ar: 'الله أكبر',
      ur: 'اللہ سب سے بڑا ہے',
    },
    recommendedCount: 34,
  },
  {
    arabic: 'لَا إِلٰهَ إِلَّا اللّٰهُ',
    transliteration: 'Lā ilāha illā Allāh',
    translation: {
      en: 'There is no deity except Allah',
      ar: 'لا إله إلا الله',
      ur: 'اللہ کے سوا کوئی معبود نہیں',
    },
    recommendedCount: 100,
  },
  {
    arabic: 'أَسْتَغْفِرُ اللّٰهَ',
    transliteration: 'Astaghfirullāh',
    translation: {
      en: 'I seek forgiveness from Allah',
      ar: 'أستغفر الله',
      ur: 'میں اللہ سے مغفرت مانگتا ہوں',
    },
    recommendedCount: 100,
  },
  {
    arabic: 'اللَّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ',
    transliteration: 'Allāhumma ṣalli ‘alā Muḥammad',
    translation: {
      en: 'O Allah, send blessings upon Muhammad',
      ar: 'اللهم صل على محمد',
      ur: 'اے اللہ، محمد ﷺ پر درود بھیج',
    },
    recommendedCount: 10,
  },
  {
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ',
    transliteration: 'Lā ḥawla wa lā quwwata illā billāh',
    translation: {
      en: 'There is no power and no strength except with Allah',
      ar: 'لا حول ولا قوة إلا بالله',
      ur: 'اللہ کے سوا کوئی طاقت اور قوت نہیں',
    },
    recommendedCount: 100,
  },
]

export const ROUTINES = [
  {
    id: 'tasbihFatimah',
    name: {
      en: 'Tasbih Fatimah',
      ar: 'تسبيح فاطمة',
      ur: 'تسبیح فاطمہ',
    },
    description: {
      en: 'Complete 33 SubhanAllah, 33 Alhamdulillah and 34 Allahu Akbar for one full tasbih.',
      ar: 'أكمل 33 سبحان الله، 33 الحمد لله، 34 الله أكبر لتسبيح كاملة.',
      ur: 'ایک مکمل تسبیح کے لیے 33 سبحان اللہ، 33 الحمد للہ، 34 اللہ اکبر مکمل کریں۔',
    },
    entries: [
      {
        arabic: 'سُبْحَانَ اللّٰهِ',
        transliteration: 'Subḥān Allāh',
        translation: {
          en: 'Glory be to Allah',
          ar: 'سبحان الله',
          ur: 'اللہ پاک ہے',
        },
        count: 33,
      },
      {
        arabic: 'الْحَمْدُ لِلّٰهِ',
        transliteration: 'Al-ḥamdu lillāh',
        translation: {
          en: 'All praise is due to Allah',
          ar: 'الحمد لله',
          ur: 'تمام تعریفیں اللہ کے لیے ہیں',
        },
        count: 33,
      },
      {
        arabic: 'اللّٰهُ أَكْبَرُ',
        transliteration: 'Allāhu akbar',
        translation: {
          en: 'Allah is the Greatest',
          ar: 'الله أكبر',
          ur: 'اللہ سب سے بڑا ہے',
        },
        count: 34,
      },
    ],
  },
  {
    id: 'morningEvening',
    name: {
      en: 'Morning & Evening Adhkar',
      ar: 'أذكار الصباح والمساء',
      ur: 'صبح و شام کے اذکار',
    },
    description: {
      en: 'A gentle sequence of essential morning and evening remembrances.',
      ar: 'تسلسل لطيف من الأذكار الأساسية للصباح والمساء.',
      ur: 'صبح و شام کے اہم اذکار کا نرم سلسلہ۔',
    },
    entries: [
      {
        arabic: 'سُبْحَانَ اللّٰهِ',
        transliteration: 'Subḥān Allāh',
        translation: {
          en: 'Glory be to Allah',
          ar: 'سبحان الله',
          ur: 'اللہ پاک ہے',
        },
        count: 33,
      },
      {
        arabic: 'الْحَمْدُ لِلّٰهِ',
        transliteration: 'Al-ḥamdu lillāh',
        translation: {
          en: 'All praise is due to Allah',
          ar: 'الحمد لله',
          ur: 'تمام تعریفیں اللہ کے لیے ہیں',
        },
        count: 33,
      },
      {
        arabic: 'اللّٰهُ أَكْبَرُ',
        transliteration: 'Allāhu akbar',
        translation: {
          en: 'Allah is the Greatest',
          ar: 'الله أكبر',
          ur: 'اللہ سب سے بڑا ہے',
        },
        count: 34,
      },
      {
        arabic: 'أَسْتَغْفِرُ اللّٰهَ',
        transliteration: 'Astaghfirullāh',
        translation: {
          en: 'I seek forgiveness from Allah',
          ar: 'أستغفر الله',
          ur: 'میں اللہ سے مغفرت مانگتا ہوں',
        },
        count: 33,
      },
      {
        arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ',
        transliteration: 'Lā ḥawla wa lā quwwata illā billāh',
        translation: {
          en: 'There is no power and no strength except with Allah',
          ar: 'لا حول ولا قوة إلا بالله',
          ur: 'اللہ کے سوا کوئی طاقت اور قوت نہیں',
        },
        count: 33,
      },
    ],
  },
]

export const ASMA_NAMES = [
  { arabic: 'الرَّحْمَـنُ', transliteration: 'Ar-Raḥmān', meaning: 'The Most Compassionate' },
  { arabic: 'الرَّحِيمُ', transliteration: 'Ar-Raḥīm', meaning: 'The Most Merciful' },
  { arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The Absolute Ruler' },
  { arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddūs', meaning: 'The Pure, Holy' },
  { arabic: 'السَّلَامُ', transliteration: 'As-Salām', meaning: 'Source of Peace and Safety' },
  { arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu’min', meaning: 'Infuser of Faith and Safety' },
  { arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymīn', meaning: 'The Guardian, Protector' },
  { arabic: 'الْعَزِيزُ', transliteration: 'Al-‘Azīz', meaning: 'The Almighty' },
  { arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbār', meaning: 'The Compeller' },
  { arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Supremely Majestic' },
  { arabic: 'الْخَالِقُ', transliteration: 'Al-Khāliq', meaning: 'The Creator' },
  { arabic: 'الْبَارِئُ', transliteration: 'Al-Bāriʼ', meaning: 'The Evolver' },
  { arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Muṣawwir', meaning: 'The Fashioner' },
  { arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffār', meaning: 'The Constant Forgiver' },
  { arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhār', meaning: 'The All-Subduer' },
  { arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhāb', meaning: 'The Bestowal Giver' },
  { arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzāq', meaning: 'The Provider' },
  { arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattāḥ', meaning: 'The Supreme Opener' },
  { arabic: 'اَلْعَلِيمُ', transliteration: 'Al-‘Alīm', meaning: 'The All-Knowing' },
  { arabic: 'الْقَابِضُ', transliteration: 'Al-Qābiḍ', meaning: 'The Withholder' },
  { arabic: 'الْبَاسِطُ', transliteration: 'Al-Bāsit', meaning: 'The Extender' },
  { arabic: 'الْخَافِضُ', transliteration: 'Al-Khāfiḍ', meaning: 'The Reducer' },
  { arabic: 'الرَّافِعُ', transliteration: 'Ar-Rāfiʿ', meaning: 'The Exalter' },
  { arabic: 'الْمُعِزُّ', transliteration: 'Al-Muʿizz', meaning: 'The Honourer' },
  { arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Dishonourer' },
  { arabic: 'السَّمِيعُ', transliteration: 'As-Samīʿ', meaning: 'The All-Hearing' },
  { arabic: 'البَصِيرُ', transliteration: 'Al-Baṣīr', meaning: 'The All-Seeing' },
  { arabic: 'الْحَكَمُ', transliteration: 'Al-Ḥakam', meaning: 'The Impartial Judge' },
  { arabic: 'الْعَدْلُ', transliteration: 'Al-‘Adl', meaning: 'The Utterly Just' },
  { arabic: 'اللَّطِيفُ', transliteration: 'Al-Laṭīf', meaning: 'The Subtle One' },
  { arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabīr', meaning: 'The All-Aware' },
  { arabic: 'الْحَلِيمُ', transliteration: 'Al-Ḥalīm', meaning: 'The Most Forbearing' },
  { arabic: 'الْعَظِيمُ', transliteration: 'Al-‘Aẓīm', meaning: 'The Magnificent' },
  { arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafūr', meaning: 'The Great Forgiver' },
  { arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakūr', meaning: 'The Most Appreciative' },
  { arabic: 'الْعَلِيُّ', transliteration: 'Al-ʿAliyy', meaning: 'The Most High' },
  { arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabīr', meaning: 'The Most Great' },
  { arabic: 'الْحَفِيظُ', transliteration: 'Al-Ḥafīẓ', meaning: 'The Preserver' },
  { arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqīt', meaning: 'The Sustainer' },
  { arabic: 'الْحَسِيبُ', transliteration: 'Al-Ḥasīb', meaning: 'The Reckoner' },
  { arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalīl', meaning: 'The Majestic' },
  { arabic: 'الْكَرِيمُ', transliteration: 'Al-Karīm', meaning: 'The Most Generous' },
  { arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqīb', meaning: 'The Watchful' },
  { arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujīb', meaning: 'The Responsive' },
  { arabic: 'الْوَاسِعُ', transliteration: 'Al-Wāsiʿ', meaning: 'The All-Encompassing' },
  { arabic: 'الْحَكِيمُ', transliteration: 'Al-Ḥakīm', meaning: 'The Perfectly Wise' },
  { arabic: 'الْوَدُودُ', transliteration: 'Al-Wadūd', meaning: 'The Most Loving' },
  { arabic: 'الْمَجِيدُ', transliteration: 'Al-Mājid', meaning: 'The Most Glorious' },
  { arabic: 'البَاعِثُ', transliteration: 'Al-Bāʿith', meaning: 'The Resurrector' },
  { arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahīd', meaning: 'The All Observing Witness' },
  { arabic: 'الْحَقُّ', transliteration: 'Al-Ḥaqq', meaning: 'The Absolute Truth' },
  { arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakīl', meaning: 'The Trustee' },
  { arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawīyy', meaning: 'The Most Strong' },
  { arabic: 'الْمَتِينُ', transliteration: 'Al-Matīn', meaning: 'The Firm One' },
  { arabic: 'الْوَلِيُّ', transliteration: 'Al-Walīyy', meaning: 'The Sole Patron' },
  { arabic: 'الْحَمِيدُ', transliteration: 'Al-Ḥamīd', meaning: 'The Praiseworthy' },
  { arabic: 'الْمُحْصِي', transliteration: 'Al-Muḥṣī', meaning: 'The Appraiser' },
  { arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdiʼ', meaning: 'The Originator' },
  { arabic: 'الْمُعِيدُ', transliteration: 'Al-Muʿīd', meaning: 'The Restorer' },
  { arabic: 'الْمُحْيِي', transliteration: 'Al-Muḥyī', meaning: 'The Giver of Life' },
  { arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumīt', meaning: 'The Creator of Death' },
  { arabic: 'الْحَيُّ', transliteration: 'Al-Ḥayy', meaning: 'The Ever-Living' },
  { arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyūm', meaning: 'The Sustainer' },
  { arabic: 'الْوَاجِدُ', transliteration: 'Al-Wājid', meaning: 'The Perceiver' },
  { arabic: 'الْمَاجِدُ', transliteration: 'Al-Mājid', meaning: 'The Glorious' },
  { arabic: 'الْواحِدُ', transliteration: 'Al-Wāḥid', meaning: 'The One' },
  { arabic: 'الْأَحَدُ', transliteration: 'Al-Aḥad', meaning: 'The Indivisible, One' },
  { arabic: 'الصَّمَدُ', transliteration: 'As-Ṣamad', meaning: 'The Self-Sufficient' },
  { arabic: 'الْقَادِرُ', transliteration: 'Al-Qādir', meaning: 'The Omnipotent' },
  { arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Creator of All Power' },
  { arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter' },
  { arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Muʼakhkhir', meaning: 'The Delayer' },
  { arabic: 'الأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First' },
  { arabic: 'الْآخِرُ', transliteration: 'Al-Ākhir', meaning: 'The Last' },
  { arabic: 'الظَّاهِرُ', transliteration: 'Aẓ-Ẓāhir', meaning: 'The Manifest' },
  { arabic: 'الْبَاطِنُ', transliteration: 'Al-Bāṭin', meaning: 'The Hidden' },
  { arabic: 'الْوَالِي', transliteration: 'Al-Wālī', meaning: 'The Sole Governor' },
  { arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta‘ālī', meaning: 'The Self-Exalted' },
  { arabic: 'الْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of All Goodness' },
  { arabic: 'التَّوَّابُ', transliteration: 'At-Tawwāb', meaning: 'The Ever-Accepter of Repentance' },
  { arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger' },
  { arabic: 'الْعَفُوُّ', transliteration: 'Al-‘Afuww', meaning: 'The Supreme Pardoner' },
  { arabic: 'الرَّؤُوفُ', transliteration: 'Ar-Ra’ūf', meaning: 'The Most Kind' },
  { arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Mālik al-Mulk', meaning: 'Master of the Kingdom' },
  { arabic: 'ذُو الْجَلَالِ وَالإِكْرَامِ', transliteration: 'Dhū al-Jalāl wa al-Ikrām', meaning: 'Lord of Glory and Honour' },
  { arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Just One' },
  { arabic: 'الْجَامِعُ', transliteration: 'Al-Jāmi‘', meaning: 'The Gatherer' },
  { arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghanīyy', meaning: 'The Self-Sufficient' },
  { arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher' },
  { arabic: 'الْمَانِعُ', transliteration: 'Al-Māni‘', meaning: 'The Preventer' },
  { arabic: 'الضَّارَّ', transliteration: 'Aḍ-Ḍārr', meaning: 'The Distresser' },
  { arabic: 'النَّافِعُ', transliteration: 'An-Nāfi‘', meaning: 'The Propitious' },
  { arabic: 'النُّورُ', transliteration: 'An-Nūr', meaning: 'The Light' },
  { arabic: 'الْهَادِي', transliteration: 'Al-Hādī', meaning: 'The Guide' },
  { arabic: 'الْبَدِيعُ', transliteration: 'Al-Badīʿ', meaning: 'The Originator' },
  { arabic: 'الْبَاقِي', transliteration: 'Al-Bāqī', meaning: 'The Everlasting' },
  { arabic: 'الوَارِثُ', transliteration: 'Al-Wārith', meaning: 'The Inheritor' },
  { arabic: 'الصَّبُورُ', transliteration: 'Aṣ-Ṣabūr', meaning: 'The Patient One' },
]
